### ISSUE TITLE
Show the created contests on the users profile page

### ISSUE THREAD

**Issue by Overbryd** [codebrawl/codebrawl#11]
Now that users can create contests on their own, everybody shall be able to see your contributions on your profile page.

**Comment by jeffkreeftmeijer** [comment]
The "submitted" contests are already being shown on the profile pages. I built this in so I could set them manually if somebody else came up with the idea. So, technically it works now.

However, I'd like to to this somewhat differently, since created Freefights aren't the same as submitted contests. Maybe we can add a "Started freefights" section? :)

**Comment by Overbryd** [comment]
Do you want freefights to coexist alongside submissions?
I mean, Freefights could get featured too. Having submissions and freefights is kinda redundant?

**Comment by jeffkreeftmeijer** [comment]
The contest submissions are very important. We need user input to be able to keep running featured contests. In my idea, the freefights don't have to confirm to the featured contest rules, use any language and everyone can do whatever they want, since, well.. they're freefights.

I'm not sure if we end up being able to use the freefights as featured contests, since the featured contests have a bunch of rules they have to follow and try to beneficial to the Ruby community. Right now I think we should keep them separate. To answer your question: yes, I think it's a good idea to let the freefights coexist alongside submissions.

As for the separation idea: I still think it might be a good idea to push the Freefights to a separate page and call it the "Freefight room" or something. Of course, we'll link to it in the navigation and at the bottom of the featured contests list.

What do you think? :)

**Comment by Overbryd** [comment]
I'm ok with that.

Lets have sponsored main contests, and the freefights area on separate pages. An on profile pages one can see submitted contests and freefights started by the user.

Showing Entries on the profile would be great too, but they don't have to be divided by contests/freefights.
