### ISSUE TITLE
Contest rundowns return errors

### ISSUE THREAD

**Issue by rstacruz** [codebrawl/codebrawl#29]
Today on IRC:

00:25:42 **nashby** joined the chat room.
00:31:00 **nashby** hey, jeff. I'm getting a 500 error when trying to open http://codebrawl.com/articles/contest-rundown-key-value-stores
00:34:38 **rstacruz** that's sad, the other contest rundowns seem to be 500'ing too
00:34:39 **rstacruz** http://codebrawl.com/articles/contest-rundown-whyday-2011
00:35:22 **nashby** yeah, somthing is broken :(

**Comment by jeffkreeftmeijer** [comment]
Hey @rstacruz and @nashby,

Thanks for letting me know. I stopped doing contest rundowns after the Travis contest because I thought I didn't really add anything. The old rundowns are still available on the [articles page](http://codebrawl.com/articles). The idea is to do some project highlights in the future, by the way.

The links on the contest pages weren't supposed to be there and they have been gone for a while but they came back after a bit of merge hell with an old branch today. Sorry about that. It has been fixed and deployed now. :)

Thanks again!
