### ISSUE TITLE
Update to Rails 3.1

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [codebrawl/codebrawl#31]
sprockets-2.0.0.beta.12 was yanked and sprockets-2.0.0 doesn't work with rails-2.1.0.rc5. Travis is failing because of this, so we need to update to Rails 3.1 to get it all working again. I gave it a quick shot this morning and it wasn't as easy as I thought because of API changes between the Rails RC and the final release. >:(

**Comment by mrrooijen** [comment]
U MAD? But seriously, Rails is failing with its dependencies lately. What helped me when upgrading to 3.1 final was to generate a bare Rails 3.1 final Rails app and copy over configuration (and remove parts of configuration that was deprecated/removed). Even more hilarious is [this](https://rubygems.org/gems/rails/versions/3.1.1.rc1), might be worth checking out since you're upgrading anyway.

**Comment by jeffkreeftmeijer** [comment]
@meskyanichi I'll probably stay on 3.1 final for a while, or at least until 3.1.1 adds something I actually need. Do you have that app you updated online somewhere? I'd love to steal some tricks from it. :)

**Comment by mrrooijen** [comment]
Only http://hirefireapp.com/ - Rails 3.1 final was released 1 day before HireFire went out of beta, managed to sneak it in just in time. ;D Though it's not open source, but I doubt there's anything you'd learn from it since I haven't really used any of the "flashy new features" other than the asset pipeline. Just wanted to move to a "stable" version of Rails, and get 3.1's performance improvements, but no the chunked responses or other new features I think.

I'm also actually staying on 3.1 final, until 3.1.1 (non-rc) comes out as it fixes some bugs (although I don't know exactly what bugs, other than the damn annoying log warnings in 3.1 which aren't harmful but pollute our (development) logs.
